name: Flutter_Tests

on:
  push:
    paths: 
      - "core/**"
      - ".github/workflows/core_test.yaml"

  pull_request:
    paths: 
      - "core/**"
      - ".github/workflows/core_test.yaml"

jobs:
  tests:
    defaults:
      run:
        working-directory: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      
      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}